### ISSUE TITLE
Errors when installed on clean El Capitan 10.11

### ISSUE THREAD

**Issue by webfed** [BrianGilbert/OSXAegirInstaller#49] opened 2015-10-05 20:09 UTC
Things go wrong when installing composer. Do you need more info?

https://gist.github.com/webfed/f0de69193619ffaac037#file-aegir-install-logfile-2015-10-log

**Comment by BrianGilbert** [comment] 2015-10-05 22:48
It looks like the issue was caused because you have php56 installed..?

**Comment by webfed** [comment] 2015-10-06 03:09
Yes, like the previous issue. That must be standard with 10.11 since the only thing I installed after the OS is Xcode. Maybe add uninstall to the script? I can test it on a clean install.
First I will reinstall 10.11 and see what is installed.

**Comment by BrianGilbert** [comment] 2015-10-06 03:11
it's erroring on 'php56' (which means it was installed via homebrew not just present in OS X)..

you can rerun the script to uninstall.

**Comment by webfed** [comment] 2015-10-06 03:13
And after that rerun the script to install Aegir you mean?

**Comment by BrianGilbert** [comment] 2015-10-06 03:15
yep, run once to install, run again to uninstall..

**Comment by webfed** [comment] 2015-10-06 03:19
But then php56 will be installed again, it happened during install of Aegir. Shouldn't there be made a change in the script to prevent this happening?

**Comment by BrianGilbert** [comment] 2015-10-06 03:22
Impossible for it to install php56, unless something in homebrew has added it as a dependancy (Looks like it may be a dependancy of composer installed via homebrew) .. if thats the case it may not be fixable very quickly.

**Comment by webfed** [comment] 2015-10-06 03:25
That must be it.
However it says version required is 5.3.2
https://getcomposer.org/doc/00-intro.md
Strange

**Comment by BrianGilbert** [comment] 2015-10-06 03:25
I looks like it php56 should only get installed if no other version is linked..  https://github.com/Homebrew/homebrew-php/blob/master/Requirements/php-meta-requirement.rb

**Comment by webfed** [comment] 2015-10-06 03:26
So I should have the installer install at least 2 versions op php?

**Comment by BrianGilbert** [comment] 2015-10-06 03:27
I think I see the issue..  give me a tic

**Comment by webfed** [comment] 2015-10-06 03:30
I am not a native english speaker, what does give me a tic mean :-)

**Comment by BrianGilbert** [comment] 2015-10-06 03:30
You'll need to uninstall, then re-download the script before installing again..

I think it was possibly because drush master branch is for Drupal 8 now.. updated it to install 7.x

**Comment by webfed** [comment] 2015-10-06 03:31
Thanks! Will try and report

**Comment by webfed** [comment] 2015-10-06 06:21
Installing only one version of php fails, so uninstalled and reinstalled.
It stopped at mysql configuration, I had to enter this to continue in another terminal window:
aegir:~ gerard$ touch /tmp/mysql.sock
aegir:~ gerard$ mysql.server start
Starting MySQL
. SUCCESS! 

After that when starting with provision drush could not be found.

https://gist.github.com/webfed/04db005bc3332e7e68e7#file-aegir-install-logfile-2015-10-06-07-51-16-log

**Comment by BrianGilbert** [comment] 2015-10-06 09:14
Issue created for root cause of install fail:
https://github.com/Homebrew/homebrew-php/issues/2437

**Comment by BrianGilbert** [comment] 2015-10-06 22:51
Confirmed as an issue with home-brew-php repo.

**Comment by michaeljs1990** [comment] 2015-10-10 20:38
I posted how to fix this in the issue you opened if you want to move forward and not wait for upstream to fix it @webfed

**Comment by webfed** [comment] 2015-10-10 21:11
@michaeljs1990 thanks, much appreciated

**Comment by BrianGilbert** [comment] 2015-10-13 20:38
@webfed The issue is now fixed upstream

**Closed by BrianGilbert** 2015-10-13 20:38 UTC
